### ISSUE TITLE
Secrets loader with secret value masking on supported CI platforms

### ISSUE THREAD

**Issue by ajhalili2006** [dotenvx/dotenvx#308]
## About this issue

I am planning to switch secrets storage from Doppler into `dotenvx` (technically `dotenv-vault` at first, but see <https://github.com/dotenvx/dotenvx/issues/259#issuecomment-2186788110> for the uninitiated) and I want to use secrets within the CI context while keeping the values masked at the logs. Based on my CI usage and experience, currently GitHub Actions support this setup with `core.setSecret` and `core.exportVariable` in `@actions/core` npm package (`echo ::add-mask::$SECRET` and `DOTENV_PRIVATE_KEY_CI=... dotenvx get -f ${DOTENV_FILE:=".env.ci"} | tee -a $GITHUB_ENV` in plain shell commands respectively). The reason behind this is that I want to use them without the need to manually sync to the CI platform's secrets management just to mask them, which defeats this project's purpose.

### Proposed Example Usage

```yaml
# This is a example usage on GitHub Actions for those reading this issue.

- uses: dotenvx/github-actions-integration@main
  id: dotenvx
  with:
    key: ${{ secrets.DOTENV_PRIVATE_KEY_CI }} # only add this on Actions secrets and nothing else
    path: .env.ci # by default

- uses: docker/login-action@main
  with:
    registry: registry.example.dev
    username: ${{ steps.dotenvx.outputs.DOCKER_USERNAME }}
    password: ${{ steps.dotenvx.outputs.DOCKER_PASSWORD }}
```

## Prior art / Related Resources

* From @DopplerHQ: <https://github.com/marketplace/actions/fetch-doppler-secrets> (sources: <https://github.com/DopplerHQ/secrets-fetch-action>
* GitHub Docs: <https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#using-workflow-commands-to-access-toolkit-functions>
