### ISSUE TITLE
[REQUEST]: consider adding a `--key` flag for passing private key

### ISSUE THREAD

**Issue by badrequest400** [dotenvx/dotenvx#510]
Firstly, I would like to say that I am loving this project and approach. Needed to implement something similar before for a past project from scratch, and it is so nice to have a convenient package like this available now.

### Request
It would be amazing if there was a way to pass the private key to `dotenvx run` via a config flag as opposed to a naming convention based env var, just like the `-f` flag.

### Context
I have a need to deploy to multiple projects that are all considered a "staging" environment. So I have env files like: `.env.staging.proj1`, `.env.staging.proj2`

In some cases (especially in CI), it may be a requirement to dynamically determine the environment we want to deal with. In some scenarios, it can be a pain to set a dynamic environment variable. I have a successful workaround using `declare`, but I was quite surprised I could only configure this using a naming convention. I have the below (redacted) working workflow manifest for Github Actions.

```yaml
    runs-on: ubuntu-latest
    strategy:
      matrix:
        gcp_project: [proj1, proj2]
    steps:
      - name: Get build info
        id: build_info
        run: |
          ...
          echo "DOTENV_ENVIRONMENT_VARIABLE_NAME=${{ format('DOTENV_PRIVATE_KEY_STAGING_{0}', matrix.gcp_project) }}" >> $GITHUB_OUTPUT
          echo "ENV_FILE_NAME=.env.staging.$SUBDOMAIN" >> $GITHUB_OUTPUT

      - name: Build
        run: |
          declare -x $DOTENV_ENVIRONMENT_VARIABLE_NAME="${{ secrets[format('DOTENV_PRIVATE_KEY_{0}', matrix.gcp_project)] }}"
          pnpm turbo run build -- $ENV_FILE_NAME
```

Under the hood `turbo` ends up calling into the below script that interpolates the correct values:

```
    "build": "run() { dotenvx run -f $1 -- vite build; }; run",
```

### Conclusion
It would be nice if the key could be passed as a dynamic __value__, as opposed to having a need for a dynamic __key name__.

**Comment by motdotla** [comment]
> It would be amazing if there was a way to pass the private key to dotenvx run via a config flag as opposed to a naming convention based env var, just like the -f flag.

It's a fair suggestion. I've considered it, but I'm also hesitant. 

So far I've leaned against adding it because its convenience makes it easy to introduce a security risk - your private key is now exposed in your shell history.

Granted:

1. to your point this would be most useful in ci workflows where that history is flushed
2. we did add `-k` flag to `encrypt/decrypt` commands

But that said, this early in the project I'm still trying to encourage teams use `.env.keys` for local/dev and set them once in production/ci/staging `env` via the tools secrets/env config (in this case GitHub Actions)

> I have a successful workaround using declare

Good workaround. Could you possibly modify to this even:

```yml
    runs-on: ubuntu-latest
    strategy:
      matrix:
        gcp_project: [proj1, proj2]
    steps:
      - name: Get build info
        id: build_info
        run: |
          ...
          echo "DOTENV_PRIVATE_KEY_PROJ1=${{ secrets.DOTENV_PRIVATE_KEY_STAGING_PROJ1 }}" >> $GITHUB_ENV
          echo "DOTENV_PRIVATE_KEY_PROJ2=${{ secrets.DOTENV_PRIVATE_KEY_STAGING_PROJ2 }}" >> $GITHUB_ENV
          echo "ENV_FILE_NAME=.env.staging.$SUBDOMAIN" >> $GITHUB_OUTPUT

      - name: Build
        run: |
          pnpm turbo run build -- $ENV_FILE_NAME
```

essentially, just duplicate both private keys in your `env` prior to running your build. no harm in that. both will be available but only the appropriate one will be used via the passed `$ENV_FILE_NAME`
