### ISSUE TITLE
simple `getter`

### ISSUE THREAD

**Issue by motdotla** [dotenvx/dotenvx#55]
i'm doing things like this with [kama](kamal-deploy.org)

```
service: myservice
image: myimage

# custom registry
registry:
  server: ghcr.io
  username: myusername
  password: <%= `dotenvx run --quiet --env-file=.env.kamal -- sh -c 'echo $KAMAL_REGISTRY_PASSWORD'`.strip %>

# customize builder
builder:
  args:
    GIT_COMMIT_HASH: <%= `git rev-parse --short HEAD`.strip %>
    GIT_TAG: <%= `git tag -l | sort -V | tail -n1`.strip %>

servers:
  - <%= `dotenvx run --quiet --env-file=.env.kamal -- sh -c 'echo $SERVER_PRODUCTION'`.strip %>

env:
  clear:
    DOTENV_KEY: <%= `dotenvx run --quiet --env-file=.env.kamal -- sh -c 'echo $DOTENV_KEY_PRODUCTION'`.strip %>
    RAILS_MASTER_KEY: <%= `dotenvx run --quiet --env-file=.env.kamal -- sh -c 'echo $RAILS_MASTER_KEY_PRODUCTION'`.strip %>

volumes:
  - "storage:/rails/storage"
 ```

add a simpler `get` command (look at how heroku and vercel do it) to make this simpler:

```
dotenvx run --quiet --env-file=.env.kamal -- sh -c 'echo $KAMAL_REGISTRY_PASSWORD'
```

more like

```
dotenvx get:KAMAK_REGISTRY_PASSWORD --env-file=.env.kamal
```

or something
