### ISSUE TITLE
Integration with Cloudflare Workers/Pages/Functions

### ISSUE THREAD

**Issue by GiS91** [dotenvx/dotenvx#574]
Hi 👋,

is there a way to make **dotenvx** work with [**Cloudflare Workers**](https://workers.cloudflare.com/) and, by extension, with [**Cloudflare Pages**](https://developers.cloudflare.com/pages/) and [**Functions**](https://developers.cloudflare.com/pages/functions/)?

They all support the injection of secrets through a **.dev.vars** file – [here](https://developers.cloudflare.com/workers/configuration/secrets/) the documentation for **Workers** and [here](https://developers.cloudflare.com/workers/configuration/secrets/#local-development-with-secrets) the documentation for **Pages/Functions** instead – which does not seem to be supported by dotenvx currently.

Thank you!

**Comment by kubk** [comment]
I use dotenvx with Cloudflare workers and can share my solution (which is far from ideal).

First of all, I turned off the automatic deployment of the worker when the repository is connected and switched to GitHub Actions instead. GitHub actions are more flexible because you can deploy when specific condition is met like tests passed or manually triggered. For that I used https://github.com/cloudflare/wrangler-action

It supports setting env variables via the following syntax:

```yml
       secrets: |
          SECRET1
          SECRET2
      env:
        SECRET1: ${{ secrets.SECRET1 }}
        SECRET2: ${{ secrets.SECRET2 }}
```

Which calls [this command](https://developers.cloudflare.com/workers/configuration/secrets/#adding-secrets-to-your-project) internally in a loop.

So the only thing we have to do here is decrypt dotenv variables on CI and pass the decrypted values using some Bash tricks. Full code:

```yml
jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    name: Deploy to Development
    if: github.event_name == 'push'
    env:
      DOTENV_PRIVATE_KEY_DEVELOPMENT: ${{ secrets.DOTENV_PRIVATE_KEY_DEVELOPMENT }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run migrations
        run: npx dotenvx run -f .env.development -- tsx migrate.ts
        working-directory: './packages/api'

      - name: Typecheck
        run: npm run typecheck -w=api

      - name: Prepare Secrets for Worker (Development)
        id: prepare_secrets_dev
        working-directory: './packages/api'
        run: |
          SECRET_NAMES=$(awk -F= '!/^#/ && !/^DOTENV_PUBLIC_KEY_DEVELOPMENT/ && NF {print $1}' .env.development)
          if [ -z "$SECRET_NAMES" ]; then
            echo "::warning::No secret names found in .env.development after filtering."
          else
            echo "WORKER_SECRET_NAMES<<EOF" >> $GITHUB_ENV
            echo "$SECRET_NAMES" >> $GITHUB_ENV
            echo "EOF" >> $GITHUB_ENV
          fi
          npx dotenvx decrypt --stdout -f .env.development | grep -v '^#' >> $GITHUB_ENV
          echo "Secrets exported to environment."

      - name: Deploy to Cloudflare Workers (Development)
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          environment: development
          secrets: ${{ env.WORKER_SECRET_NAMES || '' }}
          workingDirectory: './packages/api'
```
